Add support for insecure registries when pushing & pulling
go-vela/vela-kaniko pull request #108
Opened 2022-01-19 03:24 UTC by tmapes

This adds support to the kaniko plugin to instruct Kaniko to push or pull from insecure (http) docker registries.
This is useful for folks running Vela without a way to secure their registries with SSL and also for "home labbers" might be running Vela at home.

Should close https://github.com/go-vela/community/issues/470

Adds new string-slice parameters:
- PARAMETER_INSECURE_REGISTRIES
- KANIKO_INSECURE_REGISTRIES

With support from loading the value from disc at:
- /vela/parameters/kaniko/insecure_registries
- /vela/secrets/kaniko/insecure_registries

---
While #470 above, notes the 3 command line flags, the [kaniko docs](https://github.com/GoogleContainerTools/kaniko#--insecure-registry) would leave me to believe that if you want to allow pushing and/or pulling from an insecure registry, that just this flag alone would work, although I'm not 100% sure how to fully validate that.  
If all are required, I can certainly edit the PR to include all three.

2022-01-19 03:29 UTC, tmapes commented
I think I was correct in thinking that you can either supply the boolean flag(s) of `--insecure` (for pushes) and `--insecure-pull` (for pulls) OR provide the list of insecure registries.

[insecure-pull OR registry list check](https://github.com/GoogleContainerTools/kaniko/blob/v1.7.0/pkg/image/remote/remote.go#L61-L62)

[insecure push OR registry list check](https://github.com/GoogleContainerTools/kaniko/blob/v1.7.0/pkg/executor/push.go#L106-L112)

2022-01-19 21:56 UTC, tmapes commented
Hmm, it seems the coverage is going down because I added a new variable to main.go, but that doesn't currently have tests? Unless I'm reading this wrong 😅

2022-01-21 01:24 UTC, tmapes commented
This should be ready for review as far as I can tell, however I'm not sure how to solve the coverage issue, as `main,go` doesn't currently have any coverage 😅

2022-01-21 17:30 UTC, jbrockopp commented
> I think I was correct in thinking that you can either supply the boolean flag(s) of `--insecure` (for pushes) and `--insecure-pull` (for pulls) OR provide the list of insecure registries.
> 
> [insecure-pull OR registry list check](https://github.com/GoogleContainerTools/kaniko/blob/v1.7.0/pkg/image/remote/remote.go#L61-L62)
> 
> [insecure push OR registry list check](https://github.com/GoogleContainerTools/kaniko/blob/v1.7.0/pkg/executor/push.go#L106-L112)
> 
> Thoughts on if we should instead support just the bare flags, or require entering full 'insecure registry' hostnames?

@tmapes thanks for your contribution 🎉 

I think I'm good with your change as-is because [`--insecure-registries` works](https://github.com/GoogleContainerTools/kaniko#--insecure-registry) for both pushing and pulling 👍 

That being said, I could see value in adding support for both `--insecure` and `--insecure-pull` as well 🤷 

I'm thinking it could be annoying to provide a full list of insecure registries if someone is using enough of them 😅 

If the list was large enough, then I'd prefer to use `--insecure` and/or `--insecure-pull` over `--insecure-registries`.

Thoughts on adding support for those flags to accompany this change?

2022-01-21 17:32 UTC, tmapes commented
> > I think I was correct in thinking that you can either supply the boolean flag(s) of `--insecure` (for pushes) and `--insecure-pull` (for pulls) OR provide the list of insecure registries.
> > [insecure-pull OR registry list check](https://github.com/GoogleContainerTools/kaniko/blob/v1.7.0/pkg/image/remote/remote.go#L61-L62)
> > [insecure push OR registry list check](https://github.com/GoogleContainerTools/kaniko/blob/v1.7.0/pkg/executor/push.go#L106-L112)
> > Thoughts on if we should instead support just the bare flags, or require entering full 'insecure registry' hostnames?
> 
> @tmapes thanks for your contribution 🎉
> 
> I think I'm good with your change as-is because [`--insecure-registries` works](https://github.com/GoogleContainerTools/kaniko#--insecure-registry) for both pushing and pulling 👍
> 
> That being said, I could see value in adding support for both `--insecure` and `--insecure-pull` as well 🤷
> 
> I'm thinking it could be annoying to provide a full list of insecure registries if someone is using enough of them 😅
> 
> If the list was large enough, then I'd prefer to use `--insecure` and/or `--insecure-pull` over `--insecure-registries`.
> 
> Thoughts on adding support for those flags to accompany this change?

> If the list was large enough, then I'd prefer to use `--insecure` and/or `--insecure-pull` over `--insecure-registries`.
This is a good point. I'm not against adding both of these flags in addition.

Probably good to support the 'full' suite of insecure flags anyway.

2022-01-21 17:46 UTC, tmapes commented
Other flags added.

2022-01-21 17:53 UTC, jbrockopp approved these changes
LGTM

2022-01-24 13:45 UTC, jbrockopp requested changes

2022-01-24 13:45 UTC, jbrockopp commented on cmd/vela-kaniko/main.go
> +		},
I forgot to have you update the `DOCS.md` file with these new parameters:

https://github.com/go-vela/vela-kaniko/blob/master/DOCS.md#parameters

Could you add these to that list?

2022-01-24 17:47 UTC, kaymckay approved these changes
LGTM

2022-01-24 18:05 UTC, merged